version: "2"

volumes:
  node-red-data:
  grafana-data:
  influxdb-data:

networks:
  gateway-network:
    driver: bridge

services:
  # ------------------------------------------------------------------------------------
  # BalenaLabs WiFi-Connect
  # ------------------------------------------------------------------------------------
  wifi-connect:
    image: bh.cr/balenalabs/wifi-connect-rpi
    container_name: wifi-connect
    network_mode: host
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  # ------------------------------------------------------------------------------------
  # Eclipse Mosquitto MQTT Broker
  # ------------------------------------------------------------------------------------
  mosquitto:
    build: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    restart: unless-stopped
    networks:
      - gateway-network
    ports:
      - "1883:1883"

  # ------------------------------------------------------------------------------------
  # InfluxDB Time-series Database
  # ------------------------------------------------------------------------------------
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    restart: unless-stopped
    networks:
      - gateway-network
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      # - influxdb-etc:/etc/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=skedenadmin
      - DOCKER_INFLUXDB_INIT_PASSWORD=skedenhome
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=home
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=stentoken

  # ------------------------------------------------------------------------------------
  # Node-RED data processing and automation
  # ------------------------------------------------------------------------------------
  nodered:
    build: ./node_red
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_RAWIO
    networks:
      - gateway-network
    ports:
      - "1880:1880"
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.sysfs: "1"
      io.balena.features.supervisor-api: "1"
      io.balena.features.balena-api: "1"
    environment:
      PORT: 1880
      USERNAME: "skedenadmin"
      PASSWORD: "skedenhome"
      ENCRIPTION_KEY: "skeden"
    volumes:
      - node-red-data:/data
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"

  # ------------------------------------------------------------------------------------
  # Grafana Data Visualization
  # ------------------------------------------------------------------------------------
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    networks:
      - gateway-network
    ports:
      - "80:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_SECURITY_ADMIN_USER=skedenadmin
      - GF_SECURITY_ADMIN_PASSWORD=skedenhome
